server:
  port: 8085

security:
  jwt:
    token:
      secret-key: 53cr37
      expired-length: 3600000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/listtasks?useSSL=false&serverTimezone=UTC
    username: root
    password: 91349808
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: thdejesusferreira@gmail.com
    password: ctwc hwst yvqw woxg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
