name: Java NextDone

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: listtasks
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Dependencies and Build
        run: mvn clean install

      - name: Upload build artifacts (target/)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: target/

  sonarqube:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: target/

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v5.0.0
        with:
          args: >
            -Dsonar.projectKey=TiagoFerreirago_Task_management_system
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=tiagoferreirago
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.java.binaries=target/classes

  semgrep:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Scan
        run: semgrep scan --config=p/owasp-top-ten --no-git-ignore --metrics=off

  dockerimage:
    runs-on: ubuntu-latest
    needs: [sonarqube, semgrep]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Download jar artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: target

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
           tiagoferreira97/nextdone:latest
           tiagoferreira97/nextdone:${{ github.sha }}
           tiagoferreira97/nextdone:${{ github.ref_name }}
